### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/CameraShop#1]
## Value proposition

as a programmer i want to have a
 structured environment to work with

## Description

Setup the project with the basics

## Tasks

- [x] Install Next.js app
- [x] setup the Styled Components 
- [x] setup root variables in the Styled.js file with colors, font-sizes, font-weights
- [x] structure the components folder with every page name 
- [x] setup the font-family in the styled.js file
- [x] structure the images in the public folder with each pagename and declair the folders like “Background” or “Product”
- [x] create a Datafile in the components folder 
- [x] create a repository in github (public) with a repo description
- [x] upload all userstorys in github projects
- [x] create a vercel link for the new project
- [x] search about pros and cons of the icons: icons8 and fontawesomeicons to choose the best option for the project

## Size
small
