### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/CameraShop#2]
## Navigation Bar

as a user, i would like to have an structured 
overview about what page exist, to get to the page i want to.

## Description

- a navigationbar to navigate between the pages

## Tasks

- [x] create a branch called “create-navigation-bar”
- [x] create a file in the Landingpage named “LandingPage.js”
- [x] create a new component folder with the name “Navbar”
- [x] create a new file called “HamburgerAnimation”
- [x] create a new filed called “NavBar.js”
- [x] in the aniamation file create an animation which transforms a  menu looking icon to an X with useState
- [x] create the Navbar elements which are getting visible after clicking on the menu icon, if the menu is open the icon shows an X, by clicking the x the menu page slides out.
- [x] create the names of the pages among each other with an border on the bottom of each name
- [x] check if its better to use useMedia for the Desktopversion or to use the device state as global state
- [x] if the check is done, use the better variant to set up a desktop version
- [x] the names on the desktopversion should be beside each other
- [x] keep the break points for devices in mind:  480px, 768px, 1024px, and 1280px.
- [x] add a color variant to the names while hovering
- [x] push to the repository and merge into main

## Size
small
