### ISSUE TITLE
Homepage Introduction

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/CameraShop#3]
## Homepage Introduction

as a user i would like to have a short description about the page, 
to be able to understand what the company does

## Description

Introduction when you land on the page

## Tasks

- [x] pull the last update and create a branch called “create-homepage-intro”
- [x] create a new file in the Landingpage component called “ Introduction.js“, “Subheadlines”
- [x] create the Headline, Subheadline and the introduction text  of the first section of the page
- [x] make sure that the width is about 80% of the mobile screen
- [x] every item (text, subheadline, button) should be placed among each other, instead except the phone and mail buttons.
- [x] make sure the word “unscharf” in the headline is blured with layer blur.
- [x] put the introduction and subheadlines together to the  “LandingPage.js”
- [x] check if some components can be outsourced for the future

## Size
small
