### ISSUE TITLE
Options to rent

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/CameraShop#4]
## Example Headline

as a cameraman i would like to have the chance 
to choose the item i am searching for, 
to rent this as soon as possible

## Description

three options you can visit on the productshop, like a prefilter

## Tasks

- [x] pull the last update and create a branch with the name “create-category-section”
- [x] create a folder named Category
- [x] create files named “CategoryCards” and CategorySection.js”
- [x] go into the datafile.js and add the needet information about each card in a array (imagesource, name)
- [x] display each card with the information and sort it equal to the picture
- [x] put the headline, the text and the cards togehter to the CategorySection
- [x] push the result to the repository

## Size
small
