### ISSUE TITLE
customer testimonials

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/CameraShop#5]
## customer testimonials

as a visitor i would like to have good customer rates,
to be sure that the products are a good choice

## Description

ratings from the customers who rent a product in the past

## Tasks

- [x] pull the last update and create a branch with the name “create-customer-testimonials”
- [x] create a folder named Testimonials
- [x] create files named “TestimonialCards” and “CustomerTestimonialSection.js”
- [x] go into the datafile.js and add the needet information about each card in a array (profilpicture src, name, date, review)
- [x] display each card with the information and sort it equal to the picture
- [x] think about a react carousel to make the page more modern and dynamic, that makes sure that you can swipe between each customer review
- [x] push the result to the repository

## Size
medium
