### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/CameraShop#6]
## FAQ

as a user, i would like to have the shortest way to answer 
my questions, to be able to save time 

## Description

the most common questions and answers for the customers.

## Tasks

- [x] pull the last update and create a branch with the name “create-faq-section”
- [x] create a folder named FAQ
- [x] create files named “faqcards” and FaqSection.js”
- [x] go into the datafile.js and add the needet information about each card in a array (titel, icon, headline, descriptiontext)
- [x] display each card with the information and sort it equal to the picture
- [x] create states and change them in the map function by clicking 
- [x] on click you should see the descriptiontext with the headline
- [x] create the violin spheres to the background
- [x] push the result to the repository

## Size
small
