### ISSUE TITLE
technical help and footer

### ISSUE THREAD

**Issue by jonas8900** [jonas8900/CameraShop#7]
## technical help and footer

as a user, i would like to have the shortest way to answer 
my questions, to be able to save time 

## Description

- if a product is broken or unable to use, you need help from the customer service

## Tasks

- [x] pull the last update and 
- [x] create a branch with the name “create-footer”
- [x] create a folder named TechnicalHelp and Footer
- [x] create files named “TechnicalHelp.js” and Footer.js” in the TechnicalHelp.js 
- [x] create the headline, the text and a section for a good locking card with the number of the support 
- [x] in the Footer.js create a section with an helpbutton and a scroll to top button, these two should be beside each other 
- [x] place the adress, opening and closing times and the links like “impressum, Datenschutz” to the footer 
- [x] refactore the code of the folder Landingpage
- [x] push the result to the repository

## Size
medium
